#ifndef EFFECTSEDITOR_H
#define EFFECTSEDITOR_H

#include "applicationsession.h"
#include <zyn.common/globals.h>

enum ParamIndices
{
    None = 0,

    // Mixer
    Mixer_Volume = 1,
    Mixer_Panning = 2,

    // FX
    Reverb_Volume = 11,
    Reverb_Pan = 12,
    Reverb_Time = 12,
    Reverb_InitialDelay = 13,
    Reverb_InitialDelayFeedback = 14,
    Reverb_LowPass = 15,
    Reverb_HighPass = 16,
    Reverb_Damp = 17,

    Echo_Volume = 21,
    Echo_Pan = 22,
    Echo_Delay = 22,
    Echo_LeftRightDelay = 23,
    Echo_CrossingDelay = 24,
    Echo_Feedback = 25,
    Echo_Damp = 26,

    Chorus_Volume = 31,
    Chorus_Pan = 32,
    Chorus_LFOFrequency = 32,
    Chorus_LFORandomness = 33,
    Chorus_LeftRightPhaseDifference = 34,
    Chorus_LFODepth = 35,
    Chorus_Delay = 36,
    Chorus_Feedback = 37,
    Chorus_Subtract = 39,

    Phaser_Volume = 41,
    Phaser_Pan = 42,
    Phaser_LFOFrequency = 42,
    Phaser_LFORandomness = 43,
    Phaser_LeftRightPhaseDifference = 44,
    Phaser_LFODepth = 45,
    Phaser_Stages = 46,
    Phaser_Feedback = 47,
    Phaser_Subtract = 49,

    AlienWah_Volume = 51,
    AlienWah_Pan = 52,
    AlienWah_LFOFrequency = 52,
    AlienWah_LFORandomness = 53,
    AlienWah_LeftRightPhaseDifference = 54,
    AlienWah_LFODepth = 55,
    AlienWah_Delay = 56,
    AlienWah_Feedback = 57,
    AlienWah_Subtract = 58,
    AlienWah_Phase = 59,

    Distorsion_Volume = 61,
    Distorsion_Pan = 62,
    Distorsion_Drive = 62,
    Distorsion_Level = 63,
    Distorsion_LowPass = 64,
    Distorsion_HighPass = 65,
    Distorsion_DryWetMix = 66,

    EQ_Gain = 71,

    // System FX
    SystemFX_1_Volume = 1001,
    SystemFX_2_Volume = 1002,
    SystemFX_3_Volume = 1003,
    SystemFX_4_Volume = 1004,

    // Insert FX 1
    InsertFX_1 = 2100,

    InsertFX_1_Reverb_Volume = InsertFX_1 + Reverb_Volume,
    InsertFX_1_Reverb_Pan = InsertFX_1 + Reverb_Pan,
    InsertFX_1_Reverb_Time = InsertFX_1 + Reverb_Time,
    InsertFX_1_Reverb_InitialDelay = InsertFX_1 + Reverb_InitialDelay,
    InsertFX_1_Reverb_InitialDelayFeedback = InsertFX_1 + Reverb_InitialDelayFeedback,
    InsertFX_1_Reverb_LowPass = InsertFX_1 + Reverb_LowPass,
    InsertFX_1_Reverb_HighPass = InsertFX_1 + Reverb_HighPass,
    InsertFX_1_Reverb_Damp = InsertFX_1 + Reverb_Damp,

    InsertFX_1_Echo_Volume = InsertFX_1 + Echo_Volume,
    InsertFX_1_Echo_Pan = InsertFX_1 + Echo_Pan,
    InsertFX_1_Echo_Delay = InsertFX_1 + Echo_Delay,
    InsertFX_1_Echo_LeftRightDelay = InsertFX_1 + Echo_LeftRightDelay,
    InsertFX_1_Echo_CrossingDelay = InsertFX_1 + Echo_CrossingDelay,
    InsertFX_1_Echo_Feedback = InsertFX_1 + Echo_Feedback,
    InsertFX_1_Echo_Damp = InsertFX_1 + Echo_Damp,

    InsertFX_1_Chorus_Volume = InsertFX_1 + Chorus_Volume,
    InsertFX_1_Chorus_Pan = InsertFX_1 + Chorus_Pan,
    InsertFX_1_Chorus_LFOFrequency = InsertFX_1 + Chorus_LFOFrequency,
    InsertFX_1_Chorus_LFORandomness = InsertFX_1 + Chorus_LFORandomness,
    InsertFX_1_Chorus_LeftRightPhaseDifference = InsertFX_1 + Chorus_LeftRightPhaseDifference,
    InsertFX_1_Chorus_LFODepth = InsertFX_1 + Chorus_LFODepth,
    InsertFX_1_Chorus_Delay = InsertFX_1 + Chorus_Delay,
    InsertFX_1_Chorus_Feedback = InsertFX_1 + Chorus_Feedback,
    InsertFX_1_Chorus_Subtract = InsertFX_1 + Chorus_Subtract,

    InsertFX_1_Phaser_Volume = InsertFX_1 + Phaser_Volume,
    InsertFX_1_Phaser_Pan = InsertFX_1 + Phaser_Pan,
    InsertFX_1_Phaser_LFOFrequency = InsertFX_1 + Phaser_LFOFrequency,
    InsertFX_1_Phaser_LFORandomness = InsertFX_1 + Phaser_LFORandomness,
    InsertFX_1_Phaser_LeftRightPhaseDifference = InsertFX_1 + Phaser_LeftRightPhaseDifference,
    InsertFX_1_Phaser_LFODepth = InsertFX_1 + Phaser_LFODepth,
    InsertFX_1_Phaser_Stages = InsertFX_1 + Phaser_Stages,
    InsertFX_1_Phaser_Feedback = InsertFX_1 + Phaser_Feedback,
    InsertFX_1_Phaser_Subtract = InsertFX_1 + Phaser_Subtract,

    InsertFX_1_AlienWah_Volume = InsertFX_1 + AlienWah_Volume,
    InsertFX_1_AlienWah_Pan = InsertFX_1 + AlienWah_Pan,
    InsertFX_1_AlienWah_LFOFrequency = InsertFX_1 + AlienWah_LFOFrequency,
    InsertFX_1_AlienWah_LFORandomness = InsertFX_1 + AlienWah_LFORandomness,
    InsertFX_1_AlienWah_LeftRightPhaseDifference = InsertFX_1 + AlienWah_LeftRightPhaseDifference,
    InsertFX_1_AlienWah_LFODepth = InsertFX_1 + AlienWah_LFODepth,
    InsertFX_1_AlienWah_Delay = InsertFX_1 + AlienWah_Delay,
    InsertFX_1_AlienWah_Feedback = InsertFX_1 + AlienWah_Feedback,
    InsertFX_1_AlienWah_Subtract = InsertFX_1 + AlienWah_Subtract,
    InsertFX_1_AlienWah_Phase = InsertFX_1 + AlienWah_Phase,

    InsertFX_1_Distorsion_Volume = InsertFX_1 + Distorsion_Volume,
    InsertFX_1_Distorsion_Pan = InsertFX_1 + Distorsion_Pan,
    InsertFX_1_Distorsion_Drive = InsertFX_1 + Distorsion_Drive,
    InsertFX_1_Distorsion_Level = InsertFX_1 + Distorsion_Level,
    InsertFX_1_Distorsion_LowPass = InsertFX_1 + Distorsion_LowPass,
    InsertFX_1_Distorsion_HighPass = InsertFX_1 + Distorsion_HighPass,
    InsertFX_1_Distorsion_DryWetMix = InsertFX_1 + Distorsion_DryWetMix,

    InsertFX_1_EQ_Gain = InsertFX_1 + EQ_Gain,

    // Insert FX 2
    InsertFX_2 = 2200,

    InsertFX_2_Reverb_Volume = InsertFX_2 + Reverb_Volume,
    InsertFX_2_Reverb_Pan = InsertFX_2 + Reverb_Pan,
    InsertFX_2_Reverb_Time = InsertFX_2 + Reverb_Time,
    InsertFX_2_Reverb_InitialDelay = InsertFX_2 + Reverb_InitialDelay,
    InsertFX_2_Reverb_InitialDelayFeedback = InsertFX_2 + Reverb_InitialDelayFeedback,
    InsertFX_2_Reverb_LowPass = InsertFX_2 + Reverb_LowPass,
    InsertFX_2_Reverb_HighPass = InsertFX_2 + Reverb_HighPass,
    InsertFX_2_Reverb_Damp = InsertFX_2 + Reverb_Damp,

    InsertFX_2_Echo_Volume = InsertFX_2 + Echo_Volume,
    InsertFX_2_Echo_Pan = InsertFX_2 + Echo_Pan,
    InsertFX_2_Echo_Delay = InsertFX_2 + Echo_Delay,
    InsertFX_2_Echo_LeftRightDelay = InsertFX_2 + Echo_LeftRightDelay,
    InsertFX_2_Echo_CrossingDelay = InsertFX_2 + Echo_CrossingDelay,
    InsertFX_2_Echo_Feedback = InsertFX_2 + Echo_Feedback,
    InsertFX_2_Echo_Damp = InsertFX_2 + Echo_Damp,

    InsertFX_2_Chorus_Volume = InsertFX_2 + Chorus_Volume,
    InsertFX_2_Chorus_Pan = InsertFX_2 + Chorus_Pan,
    InsertFX_2_Chorus_LFOFrequency = InsertFX_2 + Chorus_LFOFrequency,
    InsertFX_2_Chorus_LFORandomness = InsertFX_2 + Chorus_LFORandomness,
    InsertFX_2_Chorus_LeftRightPhaseDifference = InsertFX_2 + Chorus_LeftRightPhaseDifference,
    InsertFX_2_Chorus_LFODepth = InsertFX_2 + Chorus_LFODepth,
    InsertFX_2_Chorus_Delay = InsertFX_2 + Chorus_Delay,
    InsertFX_2_Chorus_Feedback = InsertFX_2 + Chorus_Feedback,
    InsertFX_2_Chorus_Subtract = InsertFX_2 + Chorus_Subtract,

    InsertFX_2_Phaser_Volume = InsertFX_2 + Phaser_Volume,
    InsertFX_2_Phaser_Pan = InsertFX_2 + Phaser_Pan,
    InsertFX_2_Phaser_LFOFrequency = InsertFX_2 + Phaser_LFOFrequency,
    InsertFX_2_Phaser_LFORandomness = InsertFX_2 + Phaser_LFORandomness,
    InsertFX_2_Phaser_LeftRightPhaseDifference = InsertFX_2 + Phaser_LeftRightPhaseDifference,
    InsertFX_2_Phaser_LFODepth = InsertFX_2 + Phaser_LFODepth,
    InsertFX_2_Phaser_Stages = InsertFX_2 + Phaser_Stages,
    InsertFX_2_Phaser_Feedback = InsertFX_2 + Phaser_Feedback,
    InsertFX_2_Phaser_Subtract = InsertFX_2 + Phaser_Subtract,

    InsertFX_2_AlienWah_Volume = InsertFX_2 + AlienWah_Volume,
    InsertFX_2_AlienWah_Pan = InsertFX_2 + AlienWah_Pan,
    InsertFX_2_AlienWah_LFOFrequency = InsertFX_2 + AlienWah_LFOFrequency,
    InsertFX_2_AlienWah_LFORandomness = InsertFX_2 + AlienWah_LFORandomness,
    InsertFX_2_AlienWah_LeftRightPhaseDifference = InsertFX_2 + AlienWah_LeftRightPhaseDifference,
    InsertFX_2_AlienWah_LFODepth = InsertFX_2 + AlienWah_LFODepth,
    InsertFX_2_AlienWah_Delay = InsertFX_2 + AlienWah_Delay,
    InsertFX_2_AlienWah_Feedback = InsertFX_2 + AlienWah_Feedback,
    InsertFX_2_AlienWah_Subtract = InsertFX_2 + AlienWah_Subtract,
    InsertFX_2_AlienWah_Phase = InsertFX_2 + AlienWah_Phase,

    InsertFX_2_Distorsion_Volume = InsertFX_2 + Distorsion_Volume,
    InsertFX_2_Distorsion_Pan = InsertFX_2 + Distorsion_Pan,
    InsertFX_2_Distorsion_Drive = InsertFX_2 + Distorsion_Drive,
    InsertFX_2_Distorsion_Level = InsertFX_2 + Distorsion_Level,
    InsertFX_2_Distorsion_LowPass = InsertFX_2 + Distorsion_LowPass,
    InsertFX_2_Distorsion_HighPass = InsertFX_2 + Distorsion_HighPass,
    InsertFX_2_Distorsion_DryWetMix = InsertFX_2 + Distorsion_DryWetMix,

    InsertFX_2_EQ_Gain = InsertFX_2 + EQ_Gain,

    // Insert FX 3
    InsertFX_3 = 2300,

    InsertFX_3_Reverb_Volume = InsertFX_3 + Reverb_Volume,
    InsertFX_3_Reverb_Pan = InsertFX_3 + Reverb_Pan,
    InsertFX_3_Reverb_Time = InsertFX_3 + Reverb_Time,
    InsertFX_3_Reverb_InitialDelay = InsertFX_3 + Reverb_InitialDelay,
    InsertFX_3_Reverb_InitialDelayFeedback = InsertFX_3 + Reverb_InitialDelayFeedback,
    InsertFX_3_Reverb_LowPass = InsertFX_3 + Reverb_LowPass,
    InsertFX_3_Reverb_HighPass = InsertFX_3 + Reverb_HighPass,
    InsertFX_3_Reverb_Damp = InsertFX_3 + Reverb_Damp,

    InsertFX_3_Echo_Volume = InsertFX_3 + Echo_Volume,
    InsertFX_3_Echo_Pan = InsertFX_3 + Echo_Pan,
    InsertFX_3_Echo_Delay = InsertFX_3 + Echo_Delay,
    InsertFX_3_Echo_LeftRightDelay = InsertFX_3 + Echo_LeftRightDelay,
    InsertFX_3_Echo_CrossingDelay = InsertFX_3 + Echo_CrossingDelay,
    InsertFX_3_Echo_Feedback = InsertFX_3 + Echo_Feedback,
    InsertFX_3_Echo_Damp = InsertFX_3 + Echo_Damp,

    InsertFX_3_Chorus_Volume = InsertFX_3 + Chorus_Volume,
    InsertFX_3_Chorus_Pan = InsertFX_3 + Chorus_Pan,
    InsertFX_3_Chorus_LFOFrequency = InsertFX_3 + Chorus_LFOFrequency,
    InsertFX_3_Chorus_LFORandomness = InsertFX_3 + Chorus_LFORandomness,
    InsertFX_3_Chorus_LeftRightPhaseDifference = InsertFX_3 + Chorus_LeftRightPhaseDifference,
    InsertFX_3_Chorus_LFODepth = InsertFX_3 + Chorus_LFODepth,
    InsertFX_3_Chorus_Delay = InsertFX_3 + Chorus_Delay,
    InsertFX_3_Chorus_Feedback = InsertFX_3 + Chorus_Feedback,
    InsertFX_3_Chorus_Subtract = InsertFX_3 + Chorus_Subtract,

    InsertFX_3_Phaser_Volume = InsertFX_3 + Phaser_Volume,
    InsertFX_3_Phaser_Pan = InsertFX_3 + Phaser_Pan,
    InsertFX_3_Phaser_LFOFrequency = InsertFX_3 + Phaser_LFOFrequency,
    InsertFX_3_Phaser_LFORandomness = InsertFX_3 + Phaser_LFORandomness,
    InsertFX_3_Phaser_LeftRightPhaseDifference = InsertFX_3 + Phaser_LeftRightPhaseDifference,
    InsertFX_3_Phaser_LFODepth = InsertFX_3 + Phaser_LFODepth,
    InsertFX_3_Phaser_Stages = InsertFX_3 + Phaser_Stages,
    InsertFX_3_Phaser_Feedback = InsertFX_3 + Phaser_Feedback,
    InsertFX_3_Phaser_Subtract = InsertFX_3 + Phaser_Subtract,

    InsertFX_3_AlienWah_Volume = InsertFX_3 + AlienWah_Volume,
    InsertFX_3_AlienWah_Pan = InsertFX_3 + AlienWah_Pan,
    InsertFX_3_AlienWah_LFOFrequency = InsertFX_3 + AlienWah_LFOFrequency,
    InsertFX_3_AlienWah_LFORandomness = InsertFX_3 + AlienWah_LFORandomness,
    InsertFX_3_AlienWah_LeftRightPhaseDifference = InsertFX_3 + AlienWah_LeftRightPhaseDifference,
    InsertFX_3_AlienWah_LFODepth = InsertFX_3 + AlienWah_LFODepth,
    InsertFX_3_AlienWah_Delay = InsertFX_3 + AlienWah_Delay,
    InsertFX_3_AlienWah_Feedback = InsertFX_3 + AlienWah_Feedback,
    InsertFX_3_AlienWah_Subtract = InsertFX_3 + AlienWah_Subtract,
    InsertFX_3_AlienWah_Phase = InsertFX_3 + AlienWah_Phase,

    InsertFX_3_Distorsion_Volume = InsertFX_3 + Distorsion_Volume,
    InsertFX_3_Distorsion_Pan = InsertFX_3 + Distorsion_Pan,
    InsertFX_3_Distorsion_Drive = InsertFX_3 + Distorsion_Drive,
    InsertFX_3_Distorsion_Level = InsertFX_3 + Distorsion_Level,
    InsertFX_3_Distorsion_LowPass = InsertFX_3 + Distorsion_LowPass,
    InsertFX_3_Distorsion_HighPass = InsertFX_3 + Distorsion_HighPass,
    InsertFX_3_Distorsion_DryWetMix = InsertFX_3 + Distorsion_DryWetMix,

    InsertFX_3_EQ_Gain = InsertFX_3 + EQ_Gain,

    // Insert FX 4
    InsertFX_4 = 2400,

    InsertFX_4_Reverb_Volume = InsertFX_4 + Reverb_Volume,
    InsertFX_4_Reverb_Pan = InsertFX_4 + Reverb_Pan,
    InsertFX_4_Reverb_Time = InsertFX_4 + Reverb_Time,
    InsertFX_4_Reverb_InitialDelay = InsertFX_4 + Reverb_InitialDelay,
    InsertFX_4_Reverb_InitialDelayFeedback = InsertFX_4 + Reverb_InitialDelayFeedback,
    InsertFX_4_Reverb_LowPass = InsertFX_4 + Reverb_LowPass,
    InsertFX_4_Reverb_HighPass = InsertFX_4 + Reverb_HighPass,
    InsertFX_4_Reverb_Damp = InsertFX_4 + Reverb_Damp,

    InsertFX_4_Echo_Volume = InsertFX_4 + Echo_Volume,
    InsertFX_4_Echo_Pan = InsertFX_4 + Echo_Pan,
    InsertFX_4_Echo_Delay = InsertFX_4 + Echo_Delay,
    InsertFX_4_Echo_LeftRightDelay = InsertFX_4 + Echo_LeftRightDelay,
    InsertFX_4_Echo_CrossingDelay = InsertFX_4 + Echo_CrossingDelay,
    InsertFX_4_Echo_Feedback = InsertFX_4 + Echo_Feedback,
    InsertFX_4_Echo_Damp = InsertFX_4 + Echo_Damp,

    InsertFX_4_Chorus_Volume = InsertFX_4 + Chorus_Volume,
    InsertFX_4_Chorus_Pan = InsertFX_4 + Chorus_Pan,
    InsertFX_4_Chorus_LFOFrequency = InsertFX_4 + Chorus_LFOFrequency,
    InsertFX_4_Chorus_LFORandomness = InsertFX_4 + Chorus_LFORandomness,
    InsertFX_4_Chorus_LeftRightPhaseDifference = InsertFX_4 + Chorus_LeftRightPhaseDifference,
    InsertFX_4_Chorus_LFODepth = InsertFX_4 + Chorus_LFODepth,
    InsertFX_4_Chorus_Delay = InsertFX_4 + Chorus_Delay,
    InsertFX_4_Chorus_Feedback = InsertFX_4 + Chorus_Feedback,
    InsertFX_4_Chorus_Subtract = InsertFX_4 + Chorus_Subtract,

    InsertFX_4_Phaser_Volume = InsertFX_4 + Phaser_Volume,
    InsertFX_4_Phaser_Pan = InsertFX_4 + Phaser_Pan,
    InsertFX_4_Phaser_LFOFrequency = InsertFX_4 + Phaser_LFOFrequency,
    InsertFX_4_Phaser_LFORandomness = InsertFX_4 + Phaser_LFORandomness,
    InsertFX_4_Phaser_LeftRightPhaseDifference = InsertFX_4 + Phaser_LeftRightPhaseDifference,
    InsertFX_4_Phaser_LFODepth = InsertFX_4 + Phaser_LFODepth,
    InsertFX_4_Phaser_Stages = InsertFX_4 + Phaser_Stages,
    InsertFX_4_Phaser_Feedback = InsertFX_4 + Phaser_Feedback,
    InsertFX_4_Phaser_Subtract = InsertFX_4 + Phaser_Subtract,

    InsertFX_4_AlienWah_Volume = InsertFX_4 + AlienWah_Volume,
    InsertFX_4_AlienWah_Pan = InsertFX_4 + AlienWah_Pan,
    InsertFX_4_AlienWah_LFOFrequency = InsertFX_4 + AlienWah_LFOFrequency,
    InsertFX_4_AlienWah_LFORandomness = InsertFX_4 + AlienWah_LFORandomness,
    InsertFX_4_AlienWah_LeftRightPhaseDifference = InsertFX_4 + AlienWah_LeftRightPhaseDifference,
    InsertFX_4_AlienWah_LFODepth = InsertFX_4 + AlienWah_LFODepth,
    InsertFX_4_AlienWah_Delay = InsertFX_4 + AlienWah_Delay,
    InsertFX_4_AlienWah_Feedback = InsertFX_4 + AlienWah_Feedback,
    InsertFX_4_AlienWah_Subtract = InsertFX_4 + AlienWah_Subtract,
    InsertFX_4_AlienWah_Phase = InsertFX_4 + AlienWah_Phase,

    InsertFX_4_Distorsion_Volume = InsertFX_4 + Distorsion_Volume,
    InsertFX_4_Distorsion_Pan = InsertFX_4 + Distorsion_Pan,
    InsertFX_4_Distorsion_Drive = InsertFX_4 + Distorsion_Drive,
    InsertFX_4_Distorsion_Level = InsertFX_4 + Distorsion_Level,
    InsertFX_4_Distorsion_LowPass = InsertFX_4 + Distorsion_LowPass,
    InsertFX_4_Distorsion_HighPass = InsertFX_4 + Distorsion_HighPass,
    InsertFX_4_Distorsion_DryWetMix = InsertFX_4 + Distorsion_DryWetMix,

    InsertFX_4_EQ_Gain = InsertFX_4 + EQ_Gain,

    // Insert FX 5
    InsertFX_5 = 2500,

    InsertFX_5_Reverb_Volume = InsertFX_5 + Reverb_Volume,
    InsertFX_5_Reverb_Pan = InsertFX_5 + Reverb_Pan,
    InsertFX_5_Reverb_Time = InsertFX_5 + Reverb_Time,
    InsertFX_5_Reverb_InitialDelay = InsertFX_5 + Reverb_InitialDelay,
    InsertFX_5_Reverb_InitialDelayFeedback = InsertFX_5 + Reverb_InitialDelayFeedback,
    InsertFX_5_Reverb_LowPass = InsertFX_5 + Reverb_LowPass,
    InsertFX_5_Reverb_HighPass = InsertFX_5 + Reverb_HighPass,
    InsertFX_5_Reverb_Damp = InsertFX_5 + Reverb_Damp,

    InsertFX_5_Echo_Volume = InsertFX_5 + Echo_Volume,
    InsertFX_5_Echo_Pan = InsertFX_5 + Echo_Pan,
    InsertFX_5_Echo_Delay = InsertFX_5 + Echo_Delay,
    InsertFX_5_Echo_LeftRightDelay = InsertFX_5 + Echo_LeftRightDelay,
    InsertFX_5_Echo_CrossingDelay = InsertFX_5 + Echo_CrossingDelay,
    InsertFX_5_Echo_Feedback = InsertFX_5 + Echo_Feedback,
    InsertFX_5_Echo_Damp = InsertFX_5 + Echo_Damp,

    InsertFX_5_Chorus_Volume = InsertFX_5 + Chorus_Volume,
    InsertFX_5_Chorus_Pan = InsertFX_5 + Chorus_Pan,
    InsertFX_5_Chorus_LFOFrequency = InsertFX_5 + Chorus_LFOFrequency,
    InsertFX_5_Chorus_LFORandomness = InsertFX_5 + Chorus_LFORandomness,
    InsertFX_5_Chorus_LeftRightPhaseDifference = InsertFX_5 + Chorus_LeftRightPhaseDifference,
    InsertFX_5_Chorus_LFODepth = InsertFX_5 + Chorus_LFODepth,
    InsertFX_5_Chorus_Delay = InsertFX_5 + Chorus_Delay,
    InsertFX_5_Chorus_Feedback = InsertFX_5 + Chorus_Feedback,
    InsertFX_5_Chorus_Subtract = InsertFX_5 + Chorus_Subtract,

    InsertFX_5_Phaser_Volume = InsertFX_5 + Phaser_Volume,
    InsertFX_5_Phaser_Pan = InsertFX_5 + Phaser_Pan,
    InsertFX_5_Phaser_LFOFrequency = InsertFX_5 + Phaser_LFOFrequency,
    InsertFX_5_Phaser_LFORandomness = InsertFX_5 + Phaser_LFORandomness,
    InsertFX_5_Phaser_LeftRightPhaseDifference = InsertFX_5 + Phaser_LeftRightPhaseDifference,
    InsertFX_5_Phaser_LFODepth = InsertFX_5 + Phaser_LFODepth,
    InsertFX_5_Phaser_Stages = InsertFX_5 + Phaser_Stages,
    InsertFX_5_Phaser_Feedback = InsertFX_5 + Phaser_Feedback,
    InsertFX_5_Phaser_Subtract = InsertFX_5 + Phaser_Subtract,

    InsertFX_5_AlienWah_Volume = InsertFX_5 + AlienWah_Volume,
    InsertFX_5_AlienWah_Pan = InsertFX_5 + AlienWah_Pan,
    InsertFX_5_AlienWah_LFOFrequency = InsertFX_5 + AlienWah_LFOFrequency,
    InsertFX_5_AlienWah_LFORandomness = InsertFX_5 + AlienWah_LFORandomness,
    InsertFX_5_AlienWah_LeftRightPhaseDifference = InsertFX_5 + AlienWah_LeftRightPhaseDifference,
    InsertFX_5_AlienWah_LFODepth = InsertFX_5 + AlienWah_LFODepth,
    InsertFX_5_AlienWah_Delay = InsertFX_5 + AlienWah_Delay,
    InsertFX_5_AlienWah_Feedback = InsertFX_5 + AlienWah_Feedback,
    InsertFX_5_AlienWah_Subtract = InsertFX_5 + AlienWah_Subtract,
    InsertFX_5_AlienWah_Phase = InsertFX_5 + AlienWah_Phase,

    InsertFX_5_Distorsion_Volume = InsertFX_5 + Distorsion_Volume,
    InsertFX_5_Distorsion_Pan = InsertFX_5 + Distorsion_Pan,
    InsertFX_5_Distorsion_Drive = InsertFX_5 + Distorsion_Drive,
    InsertFX_5_Distorsion_Level = InsertFX_5 + Distorsion_Level,
    InsertFX_5_Distorsion_LowPass = InsertFX_5 + Distorsion_LowPass,
    InsertFX_5_Distorsion_HighPass = InsertFX_5 + Distorsion_HighPass,
    InsertFX_5_Distorsion_DryWetMix = InsertFX_5 + Distorsion_DryWetMix,

    InsertFX_5_EQ_Gain = InsertFX_5 + EQ_Gain,

    // Insert FX 6
    InsertFX_6 = 2600,

    InsertFX_6_Reverb_Volume = InsertFX_6 + Reverb_Volume,
    InsertFX_6_Reverb_Pan = InsertFX_6 + Reverb_Pan,
    InsertFX_6_Reverb_Time = InsertFX_6 + Reverb_Time,
    InsertFX_6_Reverb_InitialDelay = InsertFX_6 + Reverb_InitialDelay,
    InsertFX_6_Reverb_InitialDelayFeedback = InsertFX_6 + Reverb_InitialDelayFeedback,
    InsertFX_6_Reverb_LowPass = InsertFX_6 + Reverb_LowPass,
    InsertFX_6_Reverb_HighPass = InsertFX_6 + Reverb_HighPass,
    InsertFX_6_Reverb_Damp = InsertFX_6 + Reverb_Damp,

    InsertFX_6_Echo_Volume = InsertFX_6 + Echo_Volume,
    InsertFX_6_Echo_Pan = InsertFX_6 + Echo_Pan,
    InsertFX_6_Echo_Delay = InsertFX_6 + Echo_Delay,
    InsertFX_6_Echo_LeftRightDelay = InsertFX_6 + Echo_LeftRightDelay,
    InsertFX_6_Echo_CrossingDelay = InsertFX_6 + Echo_CrossingDelay,
    InsertFX_6_Echo_Feedback = InsertFX_6 + Echo_Feedback,
    InsertFX_6_Echo_Damp = InsertFX_6 + Echo_Damp,

    InsertFX_6_Chorus_Volume = InsertFX_6 + Chorus_Volume,
    InsertFX_6_Chorus_Pan = InsertFX_6 + Chorus_Pan,
    InsertFX_6_Chorus_LFOFrequency = InsertFX_6 + Chorus_LFOFrequency,
    InsertFX_6_Chorus_LFORandomness = InsertFX_6 + Chorus_LFORandomness,
    InsertFX_6_Chorus_LeftRightPhaseDifference = InsertFX_6 + Chorus_LeftRightPhaseDifference,
    InsertFX_6_Chorus_LFODepth = InsertFX_6 + Chorus_LFODepth,
    InsertFX_6_Chorus_Delay = InsertFX_6 + Chorus_Delay,
    InsertFX_6_Chorus_Feedback = InsertFX_6 + Chorus_Feedback,
    InsertFX_6_Chorus_Subtract = InsertFX_6 + Chorus_Subtract,

    InsertFX_6_Phaser_Volume = InsertFX_6 + Phaser_Volume,
    InsertFX_6_Phaser_Pan = InsertFX_6 + Phaser_Pan,
    InsertFX_6_Phaser_LFOFrequency = InsertFX_6 + Phaser_LFOFrequency,
    InsertFX_6_Phaser_LFORandomness = InsertFX_6 + Phaser_LFORandomness,
    InsertFX_6_Phaser_LeftRightPhaseDifference = InsertFX_6 + Phaser_LeftRightPhaseDifference,
    InsertFX_6_Phaser_LFODepth = InsertFX_6 + Phaser_LFODepth,
    InsertFX_6_Phaser_Stages = InsertFX_6 + Phaser_Stages,
    InsertFX_6_Phaser_Feedback = InsertFX_6 + Phaser_Feedback,
    InsertFX_6_Phaser_Subtract = InsertFX_6 + Phaser_Subtract,

    InsertFX_6_AlienWah_Volume = InsertFX_6 + AlienWah_Volume,
    InsertFX_6_AlienWah_Pan = InsertFX_6 + AlienWah_Pan,
    InsertFX_6_AlienWah_LFOFrequency = InsertFX_6 + AlienWah_LFOFrequency,
    InsertFX_6_AlienWah_LFORandomness = InsertFX_6 + AlienWah_LFORandomness,
    InsertFX_6_AlienWah_LeftRightPhaseDifference = InsertFX_6 + AlienWah_LeftRightPhaseDifference,
    InsertFX_6_AlienWah_LFODepth = InsertFX_6 + AlienWah_LFODepth,
    InsertFX_6_AlienWah_Delay = InsertFX_6 + AlienWah_Delay,
    InsertFX_6_AlienWah_Feedback = InsertFX_6 + AlienWah_Feedback,
    InsertFX_6_AlienWah_Subtract = InsertFX_6 + AlienWah_Subtract,
    InsertFX_6_AlienWah_Phase = InsertFX_6 + AlienWah_Phase,

    InsertFX_6_Distorsion_Volume = InsertFX_6 + Distorsion_Volume,
    InsertFX_6_Distorsion_Pan = InsertFX_6 + Distorsion_Pan,
    InsertFX_6_Distorsion_Drive = InsertFX_6 + Distorsion_Drive,
    InsertFX_6_Distorsion_Level = InsertFX_6 + Distorsion_Level,
    InsertFX_6_Distorsion_LowPass = InsertFX_6 + Distorsion_LowPass,
    InsertFX_6_Distorsion_HighPass = InsertFX_6 + Distorsion_HighPass,
    InsertFX_6_Distorsion_DryWetMix = InsertFX_6 + Distorsion_DryWetMix,

    InsertFX_6_EQ_Gain = InsertFX_6 + EQ_Gain,

    // Insert FX 7
    InsertFX_7 = 2700,

    InsertFX_7_Reverb_Volume = InsertFX_7 + Reverb_Volume,
    InsertFX_7_Reverb_Pan = InsertFX_7 + Reverb_Pan,
    InsertFX_7_Reverb_Time = InsertFX_7 + Reverb_Time,
    InsertFX_7_Reverb_InitialDelay = InsertFX_7 + Reverb_InitialDelay,
    InsertFX_7_Reverb_InitialDelayFeedback = InsertFX_7 + Reverb_InitialDelayFeedback,
    InsertFX_7_Reverb_LowPass = InsertFX_7 + Reverb_LowPass,
    InsertFX_7_Reverb_HighPass = InsertFX_7 + Reverb_HighPass,
    InsertFX_7_Reverb_Damp = InsertFX_7 + Reverb_Damp,

    InsertFX_7_Echo_Volume = InsertFX_7 + Echo_Volume,
    InsertFX_7_Echo_Pan = InsertFX_7 + Echo_Pan,
    InsertFX_7_Echo_Delay = InsertFX_7 + Echo_Delay,
    InsertFX_7_Echo_LeftRightDelay = InsertFX_7 + Echo_LeftRightDelay,
    InsertFX_7_Echo_CrossingDelay = InsertFX_7 + Echo_CrossingDelay,
    InsertFX_7_Echo_Feedback = InsertFX_7 + Echo_Feedback,
    InsertFX_7_Echo_Damp = InsertFX_7 + Echo_Damp,

    InsertFX_7_Chorus_Volume = InsertFX_7 + Chorus_Volume,
    InsertFX_7_Chorus_Pan = InsertFX_7 + Chorus_Pan,
    InsertFX_7_Chorus_LFOFrequency = InsertFX_7 + Chorus_LFOFrequency,
    InsertFX_7_Chorus_LFORandomness = InsertFX_7 + Chorus_LFORandomness,
    InsertFX_7_Chorus_LeftRightPhaseDifference = InsertFX_7 + Chorus_LeftRightPhaseDifference,
    InsertFX_7_Chorus_LFODepth = InsertFX_7 + Chorus_LFODepth,
    InsertFX_7_Chorus_Delay = InsertFX_7 + Chorus_Delay,
    InsertFX_7_Chorus_Feedback = InsertFX_7 + Chorus_Feedback,
    InsertFX_7_Chorus_Subtract = InsertFX_7 + Chorus_Subtract,

    InsertFX_7_Phaser_Volume = InsertFX_7 + Phaser_Volume,
    InsertFX_7_Phaser_Pan = InsertFX_7 + Phaser_Pan,
    InsertFX_7_Phaser_LFOFrequency = InsertFX_7 + Phaser_LFOFrequency,
    InsertFX_7_Phaser_LFORandomness = InsertFX_7 + Phaser_LFORandomness,
    InsertFX_7_Phaser_LeftRightPhaseDifference = InsertFX_7 + Phaser_LeftRightPhaseDifference,
    InsertFX_7_Phaser_LFODepth = InsertFX_7 + Phaser_LFODepth,
    InsertFX_7_Phaser_Stages = InsertFX_7 + Phaser_Stages,
    InsertFX_7_Phaser_Feedback = InsertFX_7 + Phaser_Feedback,
    InsertFX_7_Phaser_Subtract = InsertFX_7 + Phaser_Subtract,

    InsertFX_7_AlienWah_Volume = InsertFX_7 + AlienWah_Volume,
    InsertFX_7_AlienWah_Pan = InsertFX_7 + AlienWah_Pan,
    InsertFX_7_AlienWah_LFOFrequency = InsertFX_7 + AlienWah_LFOFrequency,
    InsertFX_7_AlienWah_LFORandomness = InsertFX_7 + AlienWah_LFORandomness,
    InsertFX_7_AlienWah_LeftRightPhaseDifference = InsertFX_7 + AlienWah_LeftRightPhaseDifference,
    InsertFX_7_AlienWah_LFODepth = InsertFX_7 + AlienWah_LFODepth,
    InsertFX_7_AlienWah_Delay = InsertFX_7 + AlienWah_Delay,
    InsertFX_7_AlienWah_Feedback = InsertFX_7 + AlienWah_Feedback,
    InsertFX_7_AlienWah_Subtract = InsertFX_7 + AlienWah_Subtract,
    InsertFX_7_AlienWah_Phase = InsertFX_7 + AlienWah_Phase,

    InsertFX_7_Distorsion_Volume = InsertFX_7 + Distorsion_Volume,
    InsertFX_7_Distorsion_Pan = InsertFX_7 + Distorsion_Pan,
    InsertFX_7_Distorsion_Drive = InsertFX_7 + Distorsion_Drive,
    InsertFX_7_Distorsion_Level = InsertFX_7 + Distorsion_Level,
    InsertFX_7_Distorsion_LowPass = InsertFX_7 + Distorsion_LowPass,
    InsertFX_7_Distorsion_HighPass = InsertFX_7 + Distorsion_HighPass,
    InsertFX_7_Distorsion_DryWetMix = InsertFX_7 + Distorsion_DryWetMix,

    InsertFX_7_EQ_Gain = InsertFX_7 + EQ_Gain,

    // Insert FX 8
    InsertFX_8 = 2800,

    InsertFX_8_Reverb_Volume = InsertFX_8 + Reverb_Volume,
    InsertFX_8_Reverb_Pan = InsertFX_8 + Reverb_Pan,
    InsertFX_8_Reverb_Time = InsertFX_8 + Reverb_Time,
    InsertFX_8_Reverb_InitialDelay = InsertFX_8 + Reverb_InitialDelay,
    InsertFX_8_Reverb_InitialDelayFeedback = InsertFX_8 + Reverb_InitialDelayFeedback,
    InsertFX_8_Reverb_LowPass = InsertFX_8 + Reverb_LowPass,
    InsertFX_8_Reverb_HighPass = InsertFX_8 + Reverb_HighPass,
    InsertFX_8_Reverb_Damp = InsertFX_8 + Reverb_Damp,

    InsertFX_8_Echo_Volume = InsertFX_8 + Echo_Volume,
    InsertFX_8_Echo_Pan = InsertFX_8 + Echo_Pan,
    InsertFX_8_Echo_Delay = InsertFX_8 + Echo_Delay,
    InsertFX_8_Echo_LeftRightDelay = InsertFX_8 + Echo_LeftRightDelay,
    InsertFX_8_Echo_CrossingDelay = InsertFX_8 + Echo_CrossingDelay,
    InsertFX_8_Echo_Feedback = InsertFX_8 + Echo_Feedback,
    InsertFX_8_Echo_Damp = InsertFX_8 + Echo_Damp,

    InsertFX_8_Chorus_Volume = InsertFX_8 + Chorus_Volume,
    InsertFX_8_Chorus_Pan = InsertFX_8 + Chorus_Pan,
    InsertFX_8_Chorus_LFOFrequency = InsertFX_8 + Chorus_LFOFrequency,
    InsertFX_8_Chorus_LFORandomness = InsertFX_8 + Chorus_LFORandomness,
    InsertFX_8_Chorus_LeftRightPhaseDifference = InsertFX_8 + Chorus_LeftRightPhaseDifference,
    InsertFX_8_Chorus_LFODepth = InsertFX_8 + Chorus_LFODepth,
    InsertFX_8_Chorus_Delay = InsertFX_8 + Chorus_Delay,
    InsertFX_8_Chorus_Feedback = InsertFX_8 + Chorus_Feedback,
    InsertFX_8_Chorus_Subtract = InsertFX_8 + Chorus_Subtract,

    InsertFX_8_Phaser_Volume = InsertFX_8 + Phaser_Volume,
    InsertFX_8_Phaser_Pan = InsertFX_8 + Phaser_Pan,
    InsertFX_8_Phaser_LFOFrequency = InsertFX_8 + Phaser_LFOFrequency,
    InsertFX_8_Phaser_LFORandomness = InsertFX_8 + Phaser_LFORandomness,
    InsertFX_8_Phaser_LeftRightPhaseDifference = InsertFX_8 + Phaser_LeftRightPhaseDifference,
    InsertFX_8_Phaser_LFODepth = InsertFX_8 + Phaser_LFODepth,
    InsertFX_8_Phaser_Stages = InsertFX_8 + Phaser_Stages,
    InsertFX_8_Phaser_Feedback = InsertFX_8 + Phaser_Feedback,
    InsertFX_8_Phaser_Subtract = InsertFX_8 + Phaser_Subtract,

    InsertFX_8_AlienWah_Volume = InsertFX_8 + AlienWah_Volume,
    InsertFX_8_AlienWah_Pan = InsertFX_8 + AlienWah_Pan,
    InsertFX_8_AlienWah_LFOFrequency = InsertFX_8 + AlienWah_LFOFrequency,
    InsertFX_8_AlienWah_LFORandomness = InsertFX_8 + AlienWah_LFORandomness,
    InsertFX_8_AlienWah_LeftRightPhaseDifference = InsertFX_8 + AlienWah_LeftRightPhaseDifference,
    InsertFX_8_AlienWah_LFODepth = InsertFX_8 + AlienWah_LFODepth,
    InsertFX_8_AlienWah_Delay = InsertFX_8 + AlienWah_Delay,
    InsertFX_8_AlienWah_Feedback = InsertFX_8 + AlienWah_Feedback,
    InsertFX_8_AlienWah_Subtract = InsertFX_8 + AlienWah_Subtract,
    InsertFX_8_AlienWah_Phase = InsertFX_8 + AlienWah_Phase,

    InsertFX_8_Distorsion_Volume = InsertFX_8 + Distorsion_Volume,
    InsertFX_8_Distorsion_Pan = InsertFX_8 + Distorsion_Pan,
    InsertFX_8_Distorsion_Drive = InsertFX_8 + Distorsion_Drive,
    InsertFX_8_Distorsion_Level = InsertFX_8 + Distorsion_Level,
    InsertFX_8_Distorsion_LowPass = InsertFX_8 + Distorsion_LowPass,
    InsertFX_8_Distorsion_HighPass = InsertFX_8 + Distorsion_HighPass,
    InsertFX_8_Distorsion_DryWetMix = InsertFX_8 + Distorsion_DryWetMix,

    InsertFX_8_EQ_Gain = InsertFX_8 + EQ_Gain,

    // Track FX 1
    TrackFX_1 = 3100,

    TrackFX_1_Reverb_Volume = TrackFX_1 + Reverb_Volume,
    TrackFX_1_Reverb_Pan = TrackFX_1 + Reverb_Pan,
    TrackFX_1_Reverb_Time = TrackFX_1 + Reverb_Time,
    TrackFX_1_Reverb_InitialDelay = TrackFX_1 + Reverb_InitialDelay,
    TrackFX_1_Reverb_InitialDelayFeedback = TrackFX_1 + Reverb_InitialDelayFeedback,
    TrackFX_1_Reverb_LowPass = TrackFX_1 + Reverb_LowPass,
    TrackFX_1_Reverb_HighPass = TrackFX_1 + Reverb_HighPass,
    TrackFX_1_Reverb_Damp = TrackFX_1 + Reverb_Damp,

    TrackFX_1_Echo_Volume = TrackFX_1 + Echo_Volume,
    TrackFX_1_Echo_Pan = TrackFX_1 + Echo_Pan,
    TrackFX_1_Echo_Delay = TrackFX_1 + Echo_Delay,
    TrackFX_1_Echo_LeftRightDelay = TrackFX_1 + Echo_LeftRightDelay,
    TrackFX_1_Echo_CrossingDelay = TrackFX_1 + Echo_CrossingDelay,
    TrackFX_1_Echo_Feedback = TrackFX_1 + Echo_Feedback,
    TrackFX_1_Echo_Damp = TrackFX_1 + Echo_Damp,

    TrackFX_1_Chorus_Volume = TrackFX_1 + Chorus_Volume,
    TrackFX_1_Chorus_Pan = TrackFX_1 + Chorus_Pan,
    TrackFX_1_Chorus_LFOFrequency = TrackFX_1 + Chorus_LFOFrequency,
    TrackFX_1_Chorus_LFORandomness = TrackFX_1 + Chorus_LFORandomness,
    TrackFX_1_Chorus_LeftRightPhaseDifference = TrackFX_1 + Chorus_LeftRightPhaseDifference,
    TrackFX_1_Chorus_LFODepth = TrackFX_1 + Chorus_LFODepth,
    TrackFX_1_Chorus_Delay = TrackFX_1 + Chorus_Delay,
    TrackFX_1_Chorus_Feedback = TrackFX_1 + Chorus_Feedback,
    TrackFX_1_Chorus_Subtract = TrackFX_1 + Chorus_Subtract,

    TrackFX_1_Phaser_Volume = TrackFX_1 + Phaser_Volume,
    TrackFX_1_Phaser_Pan = TrackFX_1 + Phaser_Pan,
    TrackFX_1_Phaser_LFOFrequency = TrackFX_1 + Phaser_LFOFrequency,
    TrackFX_1_Phaser_LFORandomness = TrackFX_1 + Phaser_LFORandomness,
    TrackFX_1_Phaser_LeftRightPhaseDifference = TrackFX_1 + Phaser_LeftRightPhaseDifference,
    TrackFX_1_Phaser_LFODepth = TrackFX_1 + Phaser_LFODepth,
    TrackFX_1_Phaser_Stages = TrackFX_1 + Phaser_Stages,
    TrackFX_1_Phaser_Feedback = TrackFX_1 + Phaser_Feedback,
    TrackFX_1_Phaser_Subtract = TrackFX_1 + Phaser_Subtract,

    TrackFX_1_AlienWah_Volume = TrackFX_1 + AlienWah_Volume,
    TrackFX_1_AlienWah_Pan = TrackFX_1 + AlienWah_Pan,
    TrackFX_1_AlienWah_LFOFrequency = TrackFX_1 + AlienWah_LFOFrequency,
    TrackFX_1_AlienWah_LFORandomness = TrackFX_1 + AlienWah_LFORandomness,
    TrackFX_1_AlienWah_LeftRightPhaseDifference = TrackFX_1 + AlienWah_LeftRightPhaseDifference,
    TrackFX_1_AlienWah_LFODepth = TrackFX_1 + AlienWah_LFODepth,
    TrackFX_1_AlienWah_Delay = TrackFX_1 + AlienWah_Delay,
    TrackFX_1_AlienWah_Feedback = TrackFX_1 + AlienWah_Feedback,
    TrackFX_1_AlienWah_Subtract = TrackFX_1 + AlienWah_Subtract,
    TrackFX_1_AlienWah_Phase = TrackFX_1 + AlienWah_Phase,

    TrackFX_1_Distorsion_Volume = TrackFX_1 + Distorsion_Volume,
    TrackFX_1_Distorsion_Pan = TrackFX_1 + Distorsion_Pan,
    TrackFX_1_Distorsion_Drive = TrackFX_1 + Distorsion_Drive,
    TrackFX_1_Distorsion_Level = TrackFX_1 + Distorsion_Level,
    TrackFX_1_Distorsion_LowPass = TrackFX_1 + Distorsion_LowPass,
    TrackFX_1_Distorsion_HighPass = TrackFX_1 + Distorsion_HighPass,
    TrackFX_1_Distorsion_DryWetMix = TrackFX_1 + Distorsion_DryWetMix,

    TrackFX_1_EQ_Gain = TrackFX_1 + EQ_Gain,

    // Track FX 2
    TrackFX_2 = 3200,

    TrackFX_2_Reverb_Volume = TrackFX_2 + Reverb_Volume,
    TrackFX_2_Reverb_Pan = TrackFX_2 + Reverb_Pan,
    TrackFX_2_Reverb_Time = TrackFX_2 + Reverb_Time,
    TrackFX_2_Reverb_InitialDelay = TrackFX_2 + Reverb_InitialDelay,
    TrackFX_2_Reverb_InitialDelayFeedback = TrackFX_2 + Reverb_InitialDelayFeedback,
    TrackFX_2_Reverb_LowPass = TrackFX_2 + Reverb_LowPass,
    TrackFX_2_Reverb_HighPass = TrackFX_2 + Reverb_HighPass,
    TrackFX_2_Reverb_Damp = TrackFX_2 + Reverb_Damp,

    TrackFX_2_Echo_Volume = TrackFX_2 + Echo_Volume,
    TrackFX_2_Echo_Pan = TrackFX_2 + Echo_Pan,
    TrackFX_2_Echo_Delay = TrackFX_2 + Echo_Delay,
    TrackFX_2_Echo_LeftRightDelay = TrackFX_2 + Echo_LeftRightDelay,
    TrackFX_2_Echo_CrossingDelay = TrackFX_2 + Echo_CrossingDelay,
    TrackFX_2_Echo_Feedback = TrackFX_2 + Echo_Feedback,
    TrackFX_2_Echo_Damp = TrackFX_2 + Echo_Damp,

    TrackFX_2_Chorus_Volume = TrackFX_2 + Chorus_Volume,
    TrackFX_2_Chorus_Pan = TrackFX_2 + Chorus_Pan,
    TrackFX_2_Chorus_LFOFrequency = TrackFX_2 + Chorus_LFOFrequency,
    TrackFX_2_Chorus_LFORandomness = TrackFX_2 + Chorus_LFORandomness,
    TrackFX_2_Chorus_LeftRightPhaseDifference = TrackFX_2 + Chorus_LeftRightPhaseDifference,
    TrackFX_2_Chorus_LFODepth = TrackFX_2 + Chorus_LFODepth,
    TrackFX_2_Chorus_Delay = TrackFX_2 + Chorus_Delay,
    TrackFX_2_Chorus_Feedback = TrackFX_2 + Chorus_Feedback,
    TrackFX_2_Chorus_Subtract = TrackFX_2 + Chorus_Subtract,

    TrackFX_2_Phaser_Volume = TrackFX_2 + Phaser_Volume,
    TrackFX_2_Phaser_Pan = TrackFX_2 + Phaser_Pan,
    TrackFX_2_Phaser_LFOFrequency = TrackFX_2 + Phaser_LFOFrequency,
    TrackFX_2_Phaser_LFORandomness = TrackFX_2 + Phaser_LFORandomness,
    TrackFX_2_Phaser_LeftRightPhaseDifference = TrackFX_2 + Phaser_LeftRightPhaseDifference,
    TrackFX_2_Phaser_LFODepth = TrackFX_2 + Phaser_LFODepth,
    TrackFX_2_Phaser_Stages = TrackFX_2 + Phaser_Stages,
    TrackFX_2_Phaser_Feedback = TrackFX_2 + Phaser_Feedback,
    TrackFX_2_Phaser_Subtract = TrackFX_2 + Phaser_Subtract,

    TrackFX_2_AlienWah_Volume = TrackFX_2 + AlienWah_Volume,
    TrackFX_2_AlienWah_Pan = TrackFX_2 + AlienWah_Pan,
    TrackFX_2_AlienWah_LFOFrequency = TrackFX_2 + AlienWah_LFOFrequency,
    TrackFX_2_AlienWah_LFORandomness = TrackFX_2 + AlienWah_LFORandomness,
    TrackFX_2_AlienWah_LeftRightPhaseDifference = TrackFX_2 + AlienWah_LeftRightPhaseDifference,
    TrackFX_2_AlienWah_LFODepth = TrackFX_2 + AlienWah_LFODepth,
    TrackFX_2_AlienWah_Delay = TrackFX_2 + AlienWah_Delay,
    TrackFX_2_AlienWah_Feedback = TrackFX_2 + AlienWah_Feedback,
    TrackFX_2_AlienWah_Subtract = TrackFX_2 + AlienWah_Subtract,
    TrackFX_2_AlienWah_Phase = TrackFX_2 + AlienWah_Phase,

    TrackFX_2_Distorsion_Volume = TrackFX_2 + Distorsion_Volume,
    TrackFX_2_Distorsion_Pan = TrackFX_2 + Distorsion_Pan,
    TrackFX_2_Distorsion_Drive = TrackFX_2 + Distorsion_Drive,
    TrackFX_2_Distorsion_Level = TrackFX_2 + Distorsion_Level,
    TrackFX_2_Distorsion_LowPass = TrackFX_2 + Distorsion_LowPass,
    TrackFX_2_Distorsion_HighPass = TrackFX_2 + Distorsion_HighPass,
    TrackFX_2_Distorsion_DryWetMix = TrackFX_2 + Distorsion_DryWetMix,

    TrackFX_2_EQ_Gain = TrackFX_2 + EQ_Gain,

    // Track FX 3
    TrackFX_3 = 3300,

    TrackFX_3_Reverb_Volume = TrackFX_3 + Reverb_Volume,
    TrackFX_3_Reverb_Pan = TrackFX_3 + Reverb_Pan,
    TrackFX_3_Reverb_Time = TrackFX_3 + Reverb_Time,
    TrackFX_3_Reverb_InitialDelay = TrackFX_3 + Reverb_InitialDelay,
    TrackFX_3_Reverb_InitialDelayFeedback = TrackFX_3 + Reverb_InitialDelayFeedback,
    TrackFX_3_Reverb_LowPass = TrackFX_3 + Reverb_LowPass,
    TrackFX_3_Reverb_HighPass = TrackFX_3 + Reverb_HighPass,
    TrackFX_3_Reverb_Damp = TrackFX_3 + Reverb_Damp,

    TrackFX_3_Echo_Volume = TrackFX_3 + Echo_Volume,
    TrackFX_3_Echo_Pan = TrackFX_3 + Echo_Pan,
    TrackFX_3_Echo_Delay = TrackFX_3 + Echo_Delay,
    TrackFX_3_Echo_LeftRightDelay = TrackFX_3 + Echo_LeftRightDelay,
    TrackFX_3_Echo_CrossingDelay = TrackFX_3 + Echo_CrossingDelay,
    TrackFX_3_Echo_Feedback = TrackFX_3 + Echo_Feedback,
    TrackFX_3_Echo_Damp = TrackFX_3 + Echo_Damp,

    TrackFX_3_Chorus_Volume = TrackFX_3 + Chorus_Volume,
    TrackFX_3_Chorus_Pan = TrackFX_3 + Chorus_Pan,
    TrackFX_3_Chorus_LFOFrequency = TrackFX_3 + Chorus_LFOFrequency,
    TrackFX_3_Chorus_LFORandomness = TrackFX_3 + Chorus_LFORandomness,
    TrackFX_3_Chorus_LeftRightPhaseDifference = TrackFX_3 + Chorus_LeftRightPhaseDifference,
    TrackFX_3_Chorus_LFODepth = TrackFX_3 + Chorus_LFODepth,
    TrackFX_3_Chorus_Delay = TrackFX_3 + Chorus_Delay,
    TrackFX_3_Chorus_Feedback = TrackFX_3 + Chorus_Feedback,
    TrackFX_3_Chorus_Subtract = TrackFX_3 + Chorus_Subtract,

    TrackFX_3_Phaser_Volume = TrackFX_3 + Phaser_Volume,
    TrackFX_3_Phaser_Pan = TrackFX_3 + Phaser_Pan,
    TrackFX_3_Phaser_LFOFrequency = TrackFX_3 + Phaser_LFOFrequency,
    TrackFX_3_Phaser_LFORandomness = TrackFX_3 + Phaser_LFORandomness,
    TrackFX_3_Phaser_LeftRightPhaseDifference = TrackFX_3 + Phaser_LeftRightPhaseDifference,
    TrackFX_3_Phaser_LFODepth = TrackFX_3 + Phaser_LFODepth,
    TrackFX_3_Phaser_Stages = TrackFX_3 + Phaser_Stages,
    TrackFX_3_Phaser_Feedback = TrackFX_3 + Phaser_Feedback,
    TrackFX_3_Phaser_Subtract = TrackFX_3 + Phaser_Subtract,

    TrackFX_3_AlienWah_Volume = TrackFX_3 + AlienWah_Volume,
    TrackFX_3_AlienWah_Pan = TrackFX_3 + AlienWah_Pan,
    TrackFX_3_AlienWah_LFOFrequency = TrackFX_3 + AlienWah_LFOFrequency,
    TrackFX_3_AlienWah_LFORandomness = TrackFX_3 + AlienWah_LFORandomness,
    TrackFX_3_AlienWah_LeftRightPhaseDifference = TrackFX_3 + AlienWah_LeftRightPhaseDifference,
    TrackFX_3_AlienWah_LFODepth = TrackFX_3 + AlienWah_LFODepth,
    TrackFX_3_AlienWah_Delay = TrackFX_3 + AlienWah_Delay,
    TrackFX_3_AlienWah_Feedback = TrackFX_3 + AlienWah_Feedback,
    TrackFX_3_AlienWah_Subtract = TrackFX_3 + AlienWah_Subtract,
    TrackFX_3_AlienWah_Phase = TrackFX_3 + AlienWah_Phase,

    TrackFX_3_Distorsion_Volume = TrackFX_3 + Distorsion_Volume,
    TrackFX_3_Distorsion_Pan = TrackFX_3 + Distorsion_Pan,
    TrackFX_3_Distorsion_Drive = TrackFX_3 + Distorsion_Drive,
    TrackFX_3_Distorsion_Level = TrackFX_3 + Distorsion_Level,
    TrackFX_3_Distorsion_LowPass = TrackFX_3 + Distorsion_LowPass,
    TrackFX_3_Distorsion_HighPass = TrackFX_3 + Distorsion_HighPass,
    TrackFX_3_Distorsion_DryWetMix = TrackFX_3 + Distorsion_DryWetMix,

    TrackFX_3_EQ_Gain = TrackFX_3 + EQ_Gain,
};

class EffectsAndAutomationEditor
{
public:
    EffectsAndAutomationEditor();

    void SetUp(ApplicationSession *session);
    void Render2d();

private:
    ApplicationSession *_session;

    void RenderEffect(
        int group,
        int index,
        int effect,
        ParamIndices &selectedParams);

    void RenderAutomatedParam(
        int selectedParam);
};

#endif // EFFECTSEDITOR_H
