#include "note.h"

char const *Note::NoteToString(
    unsigned int note)
{
    switch (note)
    {
        case 127:
            return "G-9";
        case 126:
            return "F#9";
        case 125:
            return "F-9";
        case 124:
            return "E-9";
        case 123:
            return "D#9";
        case 122:
            return "D-9";
        case 121:
            return "C#9";
        case 120:
            return "C-9";
        case 119:
            return "B-8";
        case 118:
            return "A#8";
        case 117:
            return "A-8";
        case 116:
            return "G#8";
        case 115:
            return "G-8";
        case 114:
            return "F#8";
        case 113:
            return "F-8";
        case 112:
            return "E-8";
        case 111:
            return "D#8";
        case 110:
            return "D-8";
        case 109:
            return "C#8";
        case 108:
            return "C-8";
        case 107:
            return "B-7";
        case 106:
            return "A#7";
        case 105:
            return "A-7";
        case 104:
            return "G#7";
        case 103:
            return "G-7";
        case 102:
            return "F#7";
        case 101:
            return "F-7";
        case 100:
            return "E-7";
        case 99:
            return "D#7";
        case 98:
            return "D-7";
        case 97:
            return "C#7";
        case 96:
            return "C-7";
        case 95:
            return "B-6";
        case 94:
            return "A#6";
        case 93:
            return "A-6";
        case 92:
            return "G#6";
        case 91:
            return "G-6";
        case 90:
            return "F#6";
        case 89:
            return "F-6";
        case 88:
            return "E-6";
        case 87:
            return "D#6";
        case 86:
            return "D-6";
        case 85:
            return "C#6";
        case 84:
            return "C-6";
        case 83:
            return "B-5";
        case 82:
            return "A#5";
        case 81:
            return "A-5";
        case 80:
            return "G#5";
        case 79:
            return "G-5";
        case 78:
            return "F#5";
        case 77:
            return "F-5";
        case 76:
            return "E-5";
        case 75:
            return "D#5";
        case 74:
            return "D-5";
        case 73:
            return "C#5";
        case 72:
            return "C-5";
        case 71:
            return "B-4";
        case 70:
            return "A#4";
        case 69:
            return "A-4";
        case 68:
            return "G#4";
        case 67:
            return "G-4";
        case 66:
            return "F#4";
        case 65:
            return "F-4";
        case 64:
            return "E-4";
        case 63:
            return "D#4";
        case 62:
            return "D-4";
        case 61:
            return "C#4";
        case 60:
            return "C-4";
        case 59:
            return "B-3";
        case 58:
            return "A#3";
        case 57:
            return "A-3";
        case 56:
            return "G#3";
        case 55:
            return "G-3";
        case 54:
            return "F#3";
        case 53:
            return "F-3";
        case 52:
            return "E-3";
        case 51:
            return "D#3";
        case 50:
            return "D-3";
        case 49:
            return "C#3";
        case 48:
            return "C-3";
        case 47:
            return "B-2";
        case 46:
            return "A#2";
        case 45:
            return "A-2";
        case 44:
            return "G#2";
        case 43:
            return "G-2";
        case 42:
            return "F#2";
        case 41:
            return "F-2";
        case 40:
            return "E-2";
        case 39:
            return "D#2";
        case 38:
            return "D-2";
        case 37:
            return "C#2";
        case 36:
            return "C-2";
        case 35:
            return "B-1";
        case 34:
            return "A#1";
        case 33:
            return "A-1";
        case 32:
            return "G#1";
        case 31:
            return "G-1";
        case 30:
            return "F#1";
        case 29:
            return "F-1";
        case 28:
            return "E-1";
        case 27:
            return "D#1";
        case 26:
            return "D-1";
        case 25:
            return "C#1";
        case 24:
            return "C-1";
        case 23:
            return "B-0";
        case 22:
            return "A#0";
        case 21:
            return "A-0";
    }
    return "---";
}

char const *Note::ValueToString(
    unsigned int value)
{
    switch (value)
    {
        case 1:
            return "1";
        case 2:
            return "2";
        case 3:
            return "3";
        case 4:
            return "4";
        case 5:
            return "5";
        case 6:
            return "6";
        case 7:
            return "7";
        case 8:
            return "8";
        case 9:
            return "9";
        case 10:
            return "a";
        case 11:
            return "b";
        case 12:
            return "c";
        case 13:
            return "d";
        case 14:
            return "e";
        case 15:
            return "f";
        case 16:
            return "10";
        case 17:
            return "11";
        case 18:
            return "12";
        case 19:
            return "13";
        case 20:
            return "14";
        case 21:
            return "15";
        case 22:
            return "16";
        case 23:
            return "17";
        case 24:
            return "18";
        case 25:
            return "19";
        case 26:
            return "1a";
        case 27:
            return "1b";
        case 28:
            return "1c";
        case 29:
            return "1d";
        case 30:
            return "1e";
        case 31:
            return "1f";
        case 32:
            return "20";
        case 33:
            return "21";
        case 34:
            return "22";
        case 35:
            return "23";
        case 36:
            return "24";
        case 37:
            return "25";
        case 38:
            return "26";
        case 39:
            return "27";
        case 40:
            return "28";
        case 41:
            return "29";
        case 42:
            return "2a";
        case 43:
            return "2b";
        case 44:
            return "2c";
        case 45:
            return "2d";
        case 46:
            return "2e";
        case 47:
            return "2f";
        case 48:
            return "30";
        case 49:
            return "31";
        case 50:
            return "32";
        case 51:
            return "33";
        case 52:
            return "34";
        case 53:
            return "35";
        case 54:
            return "36";
        case 55:
            return "37";
        case 56:
            return "38";
        case 57:
            return "39";
        case 58:
            return "3a";
        case 59:
            return "3b";
        case 60:
            return "3c";
        case 61:
            return "3d";
        case 62:
            return "3e";
        case 63:
            return "3f";
        case 64:
            return "40";
        case 65:
            return "41";
        case 66:
            return "42";
        case 67:
            return "43";
        case 68:
            return "44";
        case 69:
            return "45";
        case 70:
            return "46";
        case 71:
            return "47";
        case 72:
            return "48";
        case 73:
            return "49";
        case 74:
            return "4a";
        case 75:
            return "4b";
        case 76:
            return "4c";
        case 77:
            return "4d";
        case 78:
            return "4e";
        case 79:
            return "4f";
        case 80:
            return "50";
        case 81:
            return "51";
        case 82:
            return "52";
        case 83:
            return "53";
        case 84:
            return "54";
        case 85:
            return "55";
        case 86:
            return "56";
        case 87:
            return "57";
        case 88:
            return "58";
        case 89:
            return "59";
        case 90:
            return "5a";
        case 91:
            return "5b";
        case 92:
            return "5c";
        case 93:
            return "5d";
        case 94:
            return "5e";
        case 95:
            return "5f";
        case 96:
            return "60";
        case 97:
            return "61";
        case 98:
            return "62";
        case 99:
            return "63";
        case 100:
            return "64";
        case 101:
            return "65";
        case 102:
            return "66";
        case 103:
            return "67";
        case 104:
            return "68";
        case 105:
            return "69";
        case 106:
            return "6a";
        case 107:
            return "6b";
        case 108:
            return "6c";
        case 109:
            return "6d";
        case 110:
            return "6e";
        case 111:
            return "6f";
        case 112:
            return "70";
        case 113:
            return "71";
        case 114:
            return "72";
        case 115:
            return "73";
        case 116:
            return "74";
        case 117:
            return "75";
        case 118:
            return "76";
        case 119:
            return "77";
        case 120:
            return "78";
        case 121:
            return "79";
        case 122:
            return "7a";
        case 123:
            return "7b";
        case 124:
            return "7c";
        case 125:
            return "7d";
        case 126:
            return "7e";
        case 127:
            return "7f";
    }

    return "..";
}
